Configure notifications to Slack

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,243 +1,257 @@
 language: cpp
 sudo: false
-
 notifications:
-  recipients:
-    - roberto.d.remigio@uit.no
-    - luca.frediani@uit.no
-  email:
-    on_success: change
-    on_failure: always
-
+  slack:
+    secure: F2nQIW6SiaGdw1LjuZOlgBu8rUVMllrDG/5bhmTQP7gyETfViFBjTsHQdTle6jtdb+LudleZaG7WhdEiVcKUa834rKqDk1UOt9p6bsmgbsBZBAaxmPh01iVFhKn3ML7JLjfr1YtH7MWJcsS60cNBrohXfVKfFzNgDqZEu/llr90=
 cache:
   ccache: true
   directories:
-    - $HOME/.ccache
-
+  - "$HOME/.ccache"
 env:
   global:
-    - USE_CCACHE=1
-    - CCACHE_COMPRESS=1
-    - CCACHE_MAXSIZE=200M
-    - CCACHE_CPP2=1
-    - PYTHON_PACKAGES="pip pep8 cpp-coveralls"
-
+  - USE_CCACHE=1
+  - CCACHE_COMPRESS=1
+  - CCACHE_MAXSIZE=200M
+  - CCACHE_CPP2=1
+  - PYTHON_PACKAGES="pip pep8 cpp-coveralls"
 matrix:
   include:
-
-    # 1/ Linux Clang Builds
-    - os: linux
-      compiler: clang
-      addons: &clang35
-        apt:
-          sources: ['llvm-toolchain-precise-3.5', 'ubuntu-toolchain-r-test', 'boost-latest']
-          packages: ['clang-3.5', 'libboost1.55-all-dev', 'gfortran']
-      env: CXX_COMPILER='clang++-3.5' C_COMPILER='clang-3.5' Fortran_COMPILER='gfortran' BUILD_TYPE='release'
-
-    - os: linux
-      compiler: clang
-      addons: *clang35
-      env: CXX_COMPILER='clang++-3.5' C_COMPILER='clang-3.5' Fortran_COMPILER='gfortran' BUILD_TYPE='debug'
-
-
-    - os: linux
-      compiler: clang
-      addons: &clang36
-        apt:
-          sources: ['llvm-toolchain-precise-3.6', 'ubuntu-toolchain-r-test', 'boost-latest']
-          packages: ['clang-3.6', 'libboost1.55-all-dev', 'gfortran']
-      env: CXX_COMPILER='clang++-3.6' C_COMPILER='clang-3.6' Fortran_COMPILER='gfortran' BUILD_TYPE='release'
-
-    - os: linux
-      compiler: clang
-      addons: *clang36
-      env: CXX_COMPILER='clang++-3.6' C_COMPILER='clang-3.6' Fortran_COMPILER='gfortran' BUILD_TYPE='debug'
-
-
-    - os: linux
-      compiler: clang
-      addons: &clang37
-        apt:
-          sources: ['llvm-toolchain-precise-3.7', 'ubuntu-toolchain-r-test', 'boost-latest']
-          packages: ['clang-3.7', 'libboost1.55-all-dev', 'gfortran']
-      env: CXX_COMPILER='clang++-3.7' C_COMPILER='clang-3.7' Fortran_COMPILER='gfortran' BUILD_TYPE='release'
-
-    - os: linux
-      compiler: clang
-      addons: *clang37
-      env: CXX_COMPILER='clang++-3.7' C_COMPILER='clang-3.7' Fortran_COMPILER='gfortran' BUILD_TYPE='debug'
-
-
-    - os: linux
-      compiler: clang
-      addons: &clang38
-        apt:
-          sources: ['llvm-toolchain-precise', 'ubuntu-toolchain-r-test', 'boost-latest']
-          packages: ['clang-3.8', 'libboost1.55-all-dev', 'gfortran']
-      env: CXX_COMPILER='clang++-3.8' C_COMPILER='clang-3.8' Fortran_COMPILER='gfortran' BUILD_TYPE='release'
-
-    - os: linux
-      compiler: clang
-      addons: *clang38
-      env: CXX_COMPILER='clang++-3.8' C_COMPILER='clang-3.8' Fortran_COMPILER='gfortran' BUILD_TYPE='debug'
-
-
-    # 2/ Linux GCC Builds
-    - os: linux
-      compiler: gcc
-      addons: &gcc46
-        apt:
-          sources: ['ubuntu-toolchain-r-test', 'boost-latest']
-          packages: ['g++-4.6', 'gcc-4.6', 'libboost1.55-all-dev', 'gfortran-4.6']
-      env: CXX_COMPILER='g++-4.6' C_COMPILER='gcc-4.6' Fortran_COMPILER='gfortran-4.6' BUILD_TYPE='release'
-
-    - os: linux
-      compiler: gcc
-      addons: *gcc46
-      env: CXX_COMPILER='g++-4.6' C_COMPILER='gcc-4.6' Fortran_COMPILER='gfortran-4.6' BUILD_TYPE='debug'
-
-
-    - os: linux
-      compiler: gcc
-      addons: &gcc47
-        apt:
-          sources: ['ubuntu-toolchain-r-test', 'boost-latest']
-          packages: ['g++-4.7', 'gcc-4.7', 'libboost1.55-all-dev', 'gfortran-4.7']
-      env: CXX_COMPILER='g++-4.7' C_COMPILER='gcc-4.7' Fortran_COMPILER='gfortran-4.7' BUILD_TYPE='release'
-
-    - os: linux
-      compiler: gcc
-      addons: *gcc47
-      env: CXX_COMPILER='g++-4.7' C_COMPILER='gcc-4.7' Fortran_COMPILER='gfortran-4.7' BUILD_TYPE='debug'
-
-
-    - os: linux
-      compiler: gcc
-      addons: &gcc48
-        apt:
-          sources: ['ubuntu-toolchain-r-test', 'boost-latest']
-          packages: ['g++-4.8', 'gcc-4.8', 'libboost1.55-all-dev', 'gfortran-4.8']
-      env: CXX_COMPILER='g++-4.8' C_COMPILER='gcc-4.8' Fortran_COMPILER='gfortran-4.8' BUILD_TYPE='release'
-
-    - os: linux
-      compiler: gcc
-      addons: *gcc48
-      env: CXX_COMPILER='g++-4.8' C_COMPILER='gcc-4.8' Fortran_COMPILER='gfortran-4.8' BUILD_TYPE='debug'
-
-
-    - os: linux
-      compiler: gcc
-      addons: &gcc49
-        apt:
-          sources: ['ubuntu-toolchain-r-test', 'boost-latest']
-          packages: ['g++-4.9', 'gcc-4.9', 'libboost1.55-all-dev', 'gfortran-4.9']
-      env: CXX_COMPILER='g++-4.9' C_COMPILER='gcc-4.9' Fortran_COMPILER='gfortran-4.9' BUILD_TYPE='release'
-
-    - os: linux
-      compiler: gcc
-      addons: *gcc49
-      env: CXX_COMPILER='g++-4.9' C_COMPILER='gcc-4.9' Fortran_COMPILER='gfortran-4.9' BUILD_TYPE='debug'
-
-
-    - os: linux
-      compiler: gcc
-      addons: &gcc5
-        apt:
-          sources: ['ubuntu-toolchain-r-test', 'boost-latest']
-          packages: ['g++-5', 'gcc-5', 'libboost1.55-all-dev', 'gfortran-5']
-      env: CXX_COMPILER='g++-5' C_COMPILER='gcc-5' Fortran_COMPILER='gfortran-5' BUILD_TYPE='release'
-
-    - os: linux
-      compiler: gcc
-      addons: *gcc5
-      env: CXX_COMPILER='g++-5' C_COMPILER='gcc-5' Fortran_COMPILER='gfortran-5' BUILD_TYPE='debug'
-
-
-    # 3/ OSX Clang Builds
-    - os: osx
-      osx_image: xcode6.4
-      compiler: clang
-      env: CXX_COMPILER='clang++' C_COMPILER='clang' Fortran_COMPILER='gfortran' BUILD_TYPE='debug'
-
-    - os: osx
-      osx_image: xcode6.4
-      compiler: clang
-      env: CXX_COMPILER='clang++' C_COMPILER='clang' Fortran_COMPILER='gfortran' BUILD_TYPE='release'
-
-
-    - os: osx
-      osx_image: xcode7
-      compiler: clang
-      env: CXX_COMPILER='clang++' C_COMPILER='clang' Fortran_COMPILER='gfortran' BUILD_TYPE='debug'
-
-    - os: osx
-      osx_image: xcode7
-      compiler: clang
-      env: CXX_COMPILER='clang++' C_COMPILER='clang' Fortran_COMPILER='gfortran' BUILD_TYPE='release'
-
-
-    # 4/ OSX GCC5 Builds
-    - os: osx
-      osx_image: xcode6.4
-      compiler: gcc
-      env: CXX_COMPILER='g++-5' C_COMPILER='gcc-5' Fortran_COMPILER='gfortran' BUILD_TYPE='debug'
-
-    - os: osx
-      osx_image: xcode6.4
-      compiler: gcc
-      env: CXX_COMPILER='g++-5' C_COMPILER='gcc-5' Fortran_COMPILER='gfortran' BUILD_TYPE='release'
-
-
-    - os: osx
-      osx_image: xcode7
-      compiler: gcc
-      env: CXX_COMPILER='g++-5' C_COMPILER='gcc-5' Fortran_COMPILER='gfortran' BUILD_TYPE='debug'
-
-    - os: osx
-      osx_image: xcode7
-      compiler: gcc
-      env: CXX_COMPILER='g++-5' C_COMPILER='gcc-5' Fortran_COMPILER='gfortran' BUILD_TYPE='release'
-
-
-    # 5/ Linux GCC5 Coverage build
-    - os: linux
-      compiler: gcc
-      addons: *gcc5
-      env: CXX_COMPILER='g++-5' C_COMPILER='gcc-5' Fortran_COMPILER='gfortran-5' BUILD_TYPE='debug' COVERAGE=true
-
+  - os: linux
+    compiler: clang
+    addons: &1
+      apt:
+        sources:
+        - llvm-toolchain-precise-3.5
+        - ubuntu-toolchain-r-test
+        - boost-latest
+        packages:
+        - clang-3.5
+        - libboost1.55-all-dev
+        - gfortran
+    env: CXX_COMPILER='clang++-3.5' C_COMPILER='clang-3.5' Fortran_COMPILER='gfortran'
+      BUILD_TYPE='release'
+  - os: linux
+    compiler: clang
+    addons: *1
+    env: CXX_COMPILER='clang++-3.5' C_COMPILER='clang-3.5' Fortran_COMPILER='gfortran'
+      BUILD_TYPE='debug'
+  - os: linux
+    compiler: clang
+    addons: &2
+      apt:
+        sources:
+        - llvm-toolchain-precise-3.6
+        - ubuntu-toolchain-r-test
+        - boost-latest
+        packages:
+        - clang-3.6
+        - libboost1.55-all-dev
+        - gfortran
+    env: CXX_COMPILER='clang++-3.6' C_COMPILER='clang-3.6' Fortran_COMPILER='gfortran'
+      BUILD_TYPE='release'
+  - os: linux
+    compiler: clang
+    addons: *2
+    env: CXX_COMPILER='clang++-3.6' C_COMPILER='clang-3.6' Fortran_COMPILER='gfortran'
+      BUILD_TYPE='debug'
+  - os: linux
+    compiler: clang
+    addons: &3
+      apt:
+        sources:
+        - llvm-toolchain-precise-3.7
+        - ubuntu-toolchain-r-test
+        - boost-latest
+        packages:
+        - clang-3.7
+        - libboost1.55-all-dev
+        - gfortran
+    env: CXX_COMPILER='clang++-3.7' C_COMPILER='clang-3.7' Fortran_COMPILER='gfortran'
+      BUILD_TYPE='release'
+  - os: linux
+    compiler: clang
+    addons: *3
+    env: CXX_COMPILER='clang++-3.7' C_COMPILER='clang-3.7' Fortran_COMPILER='gfortran'
+      BUILD_TYPE='debug'
+  - os: linux
+    compiler: clang
+    addons: &4
+      apt:
+        sources:
+        - llvm-toolchain-precise
+        - ubuntu-toolchain-r-test
+        - boost-latest
+        packages:
+        - clang-3.8
+        - libboost1.55-all-dev
+        - gfortran
+    env: CXX_COMPILER='clang++-3.8' C_COMPILER='clang-3.8' Fortran_COMPILER='gfortran'
+      BUILD_TYPE='release'
+  - os: linux
+    compiler: clang
+    addons: *4
+    env: CXX_COMPILER='clang++-3.8' C_COMPILER='clang-3.8' Fortran_COMPILER='gfortran'
+      BUILD_TYPE='debug'
+  - os: linux
+    compiler: gcc
+    addons: &5
+      apt:
+        sources:
+        - ubuntu-toolchain-r-test
+        - boost-latest
+        packages:
+        - g++-4.6
+        - gcc-4.6
+        - libboost1.55-all-dev
+        - gfortran-4.6
+    env: CXX_COMPILER='g++-4.6' C_COMPILER='gcc-4.6' Fortran_COMPILER='gfortran-4.6'
+      BUILD_TYPE='release'
+  - os: linux
+    compiler: gcc
+    addons: *5
+    env: CXX_COMPILER='g++-4.6' C_COMPILER='gcc-4.6' Fortran_COMPILER='gfortran-4.6'
+      BUILD_TYPE='debug'
+  - os: linux
+    compiler: gcc
+    addons: &6
+      apt:
+        sources:
+        - ubuntu-toolchain-r-test
+        - boost-latest
+        packages:
+        - g++-4.7
+        - gcc-4.7
+        - libboost1.55-all-dev
+        - gfortran-4.7
+    env: CXX_COMPILER='g++-4.7' C_COMPILER='gcc-4.7' Fortran_COMPILER='gfortran-4.7'
+      BUILD_TYPE='release'
+  - os: linux
+    compiler: gcc
+    addons: *6
+    env: CXX_COMPILER='g++-4.7' C_COMPILER='gcc-4.7' Fortran_COMPILER='gfortran-4.7'
+      BUILD_TYPE='debug'
+  - os: linux
+    compiler: gcc
+    addons: &7
+      apt:
+        sources:
+        - ubuntu-toolchain-r-test
+        - boost-latest
+        packages:
+        - g++-4.8
+        - gcc-4.8
+        - libboost1.55-all-dev
+        - gfortran-4.8
+    env: CXX_COMPILER='g++-4.8' C_COMPILER='gcc-4.8' Fortran_COMPILER='gfortran-4.8'
+      BUILD_TYPE='release'
+  - os: linux
+    compiler: gcc
+    addons: *7
+    env: CXX_COMPILER='g++-4.8' C_COMPILER='gcc-4.8' Fortran_COMPILER='gfortran-4.8'
+      BUILD_TYPE='debug'
+  - os: linux
+    compiler: gcc
+    addons: &8
+      apt:
+        sources:
+        - ubuntu-toolchain-r-test
+        - boost-latest
+        packages:
+        - g++-4.9
+        - gcc-4.9
+        - libboost1.55-all-dev
+        - gfortran-4.9
+    env: CXX_COMPILER='g++-4.9' C_COMPILER='gcc-4.9' Fortran_COMPILER='gfortran-4.9'
+      BUILD_TYPE='release'
+  - os: linux
+    compiler: gcc
+    addons: *8
+    env: CXX_COMPILER='g++-4.9' C_COMPILER='gcc-4.9' Fortran_COMPILER='gfortran-4.9'
+      BUILD_TYPE='debug'
+  - os: linux
+    compiler: gcc
+    addons: &9
+      apt:
+        sources:
+        - ubuntu-toolchain-r-test
+        - boost-latest
+        packages:
+        - g++-5
+        - gcc-5
+        - libboost1.55-all-dev
+        - gfortran-5
+    env: CXX_COMPILER='g++-5' C_COMPILER='gcc-5' Fortran_COMPILER='gfortran-5' BUILD_TYPE='release'
+  - os: linux
+    compiler: gcc
+    addons: *9
+    env: CXX_COMPILER='g++-5' C_COMPILER='gcc-5' Fortran_COMPILER='gfortran-5' BUILD_TYPE='debug'
+  - os: osx
+    osx_image: xcode6.4
+    compiler: clang
+    env: CXX_COMPILER='clang++' C_COMPILER='clang' Fortran_COMPILER='gfortran' BUILD_TYPE='debug'
+  - os: osx
+    osx_image: xcode6.4
+    compiler: clang
+    env: CXX_COMPILER='clang++' C_COMPILER='clang' Fortran_COMPILER='gfortran' BUILD_TYPE='release'
+  - os: osx
+    osx_image: xcode7
+    compiler: clang
+    env: CXX_COMPILER='clang++' C_COMPILER='clang' Fortran_COMPILER='gfortran' BUILD_TYPE='debug'
+  - os: osx
+    osx_image: xcode7
+    compiler: clang
+    env: CXX_COMPILER='clang++' C_COMPILER='clang' Fortran_COMPILER='gfortran' BUILD_TYPE='release'
+  - os: osx
+    osx_image: xcode6.4
+    compiler: gcc
+    env: CXX_COMPILER='g++-5' C_COMPILER='gcc-5' Fortran_COMPILER='gfortran' BUILD_TYPE='debug'
+  - os: osx
+    osx_image: xcode6.4
+    compiler: gcc
+    env: CXX_COMPILER='g++-5' C_COMPILER='gcc-5' Fortran_COMPILER='gfortran' BUILD_TYPE='release'
+  - os: osx
+    osx_image: xcode7
+    compiler: gcc
+    env: CXX_COMPILER='g++-5' C_COMPILER='gcc-5' Fortran_COMPILER='gfortran' BUILD_TYPE='debug'
+  - os: osx
+    osx_image: xcode7
+    compiler: gcc
+    env: CXX_COMPILER='g++-5' C_COMPILER='gcc-5' Fortran_COMPILER='gfortran' BUILD_TYPE='release'
+  - os: linux
+    compiler: gcc
+    addons: *9
+    env: CXX_COMPILER='g++-5' C_COMPILER='gcc-5' Fortran_COMPILER='gfortran-5' BUILD_TYPE='debug'
+      COVERAGE=true
 install:
-  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
-  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
-  - |
-    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
-      CMAKE_URL="http://www.cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz"
-      mkdir cmake && travis_retry wget --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
-      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
-      pip install --upgrade ${PYTHON_PACKAGES} --user `whoami`
-    elif [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
-      brew install cmake boost python gcc
-      pip install --upgrade ${PYTHON_PACKAGES}
-    fi
-
+- DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
+- mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
+- |
+  if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
+    CMAKE_URL="http://www.cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz"
+    mkdir cmake && travis_retry wget --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
+    export PATH=${DEPS_DIR}/cmake/bin:${PATH}
+    pip install --upgrade ${PYTHON_PACKAGES} --user `whoami`
+  elif [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
+    brew install cmake boost python gcc
+    pip install --upgrade ${PYTHON_PACKAGES}
+  fi
 before_script:
-  - cd ${TRAVIS_BUILD_DIR}
-  - export CXX=${CXX_COMPILER}
-  - export CC=${C_COMPILER}
-  - export FC=${Fortran_COMPILER}
-  - |
-    if [[ "${COVERAGE}" = true ]]; then
-      python setup.py --cxx=${CXX_COMPILER} --cc=${C_COMPILER} --fc=${Fortran_COMPILER} --type=${BUILD_TYPE} --cmake-options='-Hprojects/CMake -DENABLE_FORTRAN_API=ON' --coverage
-    else
-      python setup.py --cxx=${CXX_COMPILER} --cc=${C_COMPILER} --fc=${Fortran_COMPILER} --type=${BUILD_TYPE} --cmake-options='-Hprojects/CMake -DENABLE_FORTRAN_API=ON'
-    fi
-  - cd build
-
+- cd ${TRAVIS_BUILD_DIR}
+- export CXX=${CXX_COMPILER}
+- export CC=${C_COMPILER}
+- export FC=${Fortran_COMPILER}
+- |
+  if [[ "${COVERAGE}" = true ]]; then
+    python setup.py --cxx=${CXX_COMPILER} --cc=${C_COMPILER} --fc=${Fortran_COMPILER} --type=${BUILD_TYPE} --cmake-options='-Hprojects/CMake -DENABLE_FORTRAN_API=ON' --coverage
+  else
+    python setup.py --cxx=${CXX_COMPILER} --cc=${C_COMPILER} --fc=${Fortran_COMPILER} --type=${BUILD_TYPE} --cmake-options='-Hprojects/CMake -DENABLE_FORTRAN_API=ON'
+  fi
+- cd build
 script:
-  - VERBOSE=1 make -j 2
-  - ctest -V -j 2
-
+- VERBOSE=1 make -j 2
+- ctest -V -j 2
 after_success:
-  - |
-    if [[ "${COVERAGE}" = true ]]; then
-      coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*generated.*" -E ".*tests*" -E ".*tools.*" -E ".*cmake*" -E ".*doc*" -E ".*examples*" || echo 'coveralls upload failed.'
-    fi
+- |
+  if [[ "${COVERAGE}" = true ]]; then
+    coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*generated.*" -E ".*tests*" -E ".*tools.*" -E ".*cmake*" -E ".*doc*" -E ".*examples*" || echo 'coveralls upload failed.'
+  fi
